#!/usr/bin/env bash
# omarchy-arm-install.sh — install Omarchy ARM from the live ISO onto a disk.
#
# Runs INSIDE the live environment as root (ships on the ISO next to this
# builder's output). First boot of the installed system runs Omarchy's own
# first-boot wizard (user creation), so this script stops at a bootable disk.
#
# usage: sudo omarchy-arm-install /dev/sdX [--hostname NAME] [--yes]
# MIT licensed (part of omarchy-parallels, unofficial community tooling).
set -euo pipefail

TARGET=""; HOSTNAME="omarchy-arm"; YES=0
log()  { printf '\033[1;32m==>\033[0m \033[1m%s\033[0m\n' "$*"; }
die()  { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --hostname) HOSTNAME="$2"; shift 2 ;;
    --yes) YES=1; shift ;;
    -h|--help) echo "usage: $0 /dev/sdX [--hostname NAME] [--yes]"; exit 0 ;;
    /dev/*) TARGET="$1"; shift ;;
    *) die "unknown argument: $1" ;;
  esac
done

[[ "$(id -u)" == "0" ]] || die "run as root"
[[ -b "$TARGET" ]] || die "target is not a block device: $TARGET"
for t in sgdisk mkfs.fat mkfs.ext4 unsquashfs bootctl blkid; do
  command -v "$t" >/dev/null || die "missing tool: $t"
done
ROOT_SRC=$(findmnt -n -o SOURCE / 2>/dev/null || echo none)
if [[ "$TARGET" == "$ROOT_SRC"* ]] || grep -q "^$TARGET" /proc/mounts; then
  die "$TARGET looks like the live boot device ($ROOT_SRC) — refusing"
fi
[[ "$TARGET" =~ ^/dev/(sd[a-z]|vd[a-z]|nvme[0-9]n[0-9]|mmcblk[0-9])$ ]] \
  || die "target must be a whole disk (got $TARGET)"

if [[ "$YES" != "1" ]]; then
  echo "About to ERASE $TARGET and install Omarchy ARM (hostname: $HOSTNAME)."
  read -rp "Type the device name to confirm (e.g. $(basename "$TARGET")): " ans
  [[ "$ans" == "$(basename "$TARGET")" ]] || die "aborted"
fi

MNT=/mnt/omroot
umount -R "$MNT" 2>/dev/null || true; mkdir -p "$MNT"

log "partitioning $TARGET (1G ESP + rest ext4)"
sgdisk -Z "$TARGET" >/dev/null
sgdisk -n1:0:+1G -t1:ef00 -c1:ESP "$TARGET" >/dev/null
sgdisk -n2:0:0 -t2:8300 -c2:rootfs "$TARGET" >/dev/null
partprobe "$TARGET" 2>/dev/null; sleep 2
case "$TARGET" in *nvme*|*mmcblk*) P1="${TARGET}p1"; P2="${TARGET}p2";; *) P1="${TARGET}1"; P2="${TARGET}2";; esac

log "formatting"
mkfs.fat -F 32 -n OMARCHYEFI "$P1" >/dev/null
mkfs.ext4 -q -L omarchy "$P2"

log "extracting rootfs (unsquashfs, a few minutes)"
mount "$P2" "$MNT"
# locate the squashfs: the live /init mounts it from the CD, but the /iso
# mountpoint does not survive switch_root — so re-discover it (loop backing
# file first, then re-mount the live CD)
find_sfs() {
  [ -f /omarchy.sfs ] && { echo /omarchy.sfs; return 0; }
  for l in /dev/loop*; do
    bf=$(losetup -n -O BACK-FILE "$l" 2>/dev/null)
    case "$bf" in *.sfs) [ -f "$bf" ] && { echo "$bf"; return 0; };; esac
  done
  for d in /dev/sr[0-9]*; do
    [ -b "$d" ] || continue
    mkdir -p /mnt/livecd
    if mount -t iso9660 -o ro "$d" /mnt/livecd 2>/dev/null \
       && [ -f /mnt/livecd/omarchy.sfs ]; then
      echo /mnt/livecd/omarchy.sfs; return 0
    fi
    umount /mnt/livecd 2>/dev/null
  done
  return 1
}
SFS=$(find_sfs) || die "omarchy.sfs not found (is the live ISO attached?)"
log "source: $SFS"
unsquashfs -f -d "$MNT" "$SFS" 2>&1 | tail -1

log "bootloader (systemd-boot for AArch64)"
mkdir -p "$MNT/boot"
mount "$P1" "$MNT/boot"
bootctl install --esp-path="$MNT/boot" --no-variables >/dev/null
# kernel + stock initramfs ride along inside the snapshot's /boot
ROOT_UUID=$(blkid -s UUID -o value "$P2")
ESP_UUID=$(blkid -s UUID -o value "$P1")
cat > "$MNT/boot/loader/loader.conf" <<EOF
timeout 3
default arch
console-mode keep
EOF
cat > "$MNT/boot/loader/entries/arch.conf" <<EOF
title   Omarchy ARM
linux   /Image
initrd  /initramfs-linux.img
options root=UUID=$ROOT_UUID rootfstype=ext4 rw rootwait console=tty0 loglevel=4 systemd.show_status=false rd.systemd.show_status=false mitigations=off nowatchdog
EOF
cat > "$MNT/etc/fstab" <<EOF
UUID=$ROOT_UUID / ext4 rw,relatime 0 1
UUID=$ESP_UUID /boot vfat rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro 0 2
EOF
echo "$HOSTNAME" > "$MNT/etc/hostname"
: > "$MNT/etc/machine-id"
rm -f "$MNT"/etc/ssh/ssh_host_*          # regenerated by sshdgenkeys.service
rm -rf "$MNT"/root/.ssh                  # never ship live/test keys
sync
umount -R "$MNT"
log "done! Remove the ISO and reboot — first boot runs Omarchy's setup wizard."
